#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'luabit'

def options(opt):
	return

def configure(conf):
	if conf.env.DEST_OS in ["linux", "android", "freebsd", "osx"]:
		conf.define( "LUA_USE_LINUX", 1 )
	return

def build(bld):
	source = [
		"bit.c"
	]

	includes = [
		'.',
		'./src',
		'../public',
		'../common'
	]

	defines = []

	libs = ['lua']
	
	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

