#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'vbsp'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, ['vbsp.vpc'], '../..' )
   
    
	includes = [
		'.',
		'../common',
		'../vmpi',
		'../../public',
		'../../fdglib',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/mathlib'
	]

	libs = [
		'bitmap',
		'fgdlib',
		'mathlib',
		'vstdlib',
		'tier2',
		'tier0',
		'tier1',
		'vtf',
        'lzma',
        'USER32',
        'SHELL32',
		'utils/lzma'
	]
	install_path = bld.env.LIBDIR
	source = []
	source += game["sources"] + ['../../public/tier0/memoverride.cpp']
	includes += game["includes"]
	defines = game["defines"]
	source.remove('../../public/bspfile.h')
	source.remove('./notes.txt')
	#defines.remove('PROTECTED_THINGS_ENABLE')
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name	 = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use	  = libs,
		install_path = install_path,
		subsystem = 'CONSOLE,5.01',
		idx	  = bld.get_taskgen_count()
	)

