#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'scripting'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = []
	

	includes = [
		'.',
		'../public',
		'../public/tier0',
	]

	defines = []

	if bld.env.DEST_OS != 'win32':
		libs = ['DL']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

